name: "Python CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      PIP_NO_CACHE_DIR: false
      PIP_USER: 1
      PYTHONUSERBASE: ${{ github.workspace }}/.cache/py-user-base
      PRE_COMMIT_HOME: ${{ github.workspace }}/.cache/pre-commit-cache

    steps:
      - name: "Add custom PYTHONUSERBASE to PATH"
        run: echo '${{ env.PYTHONUSERBASE }}/bin/' >> $GITHUB_PATH

      - name: "Checkout repository"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: "Setup Python"
        id: python
        uses: HassanAbouelela/actions/setup-python@setup-python_v1.4.2 # 1.4.0
        with:
          python_version: '3.x'
          install_args: "--with dev"

      # As pre-commit does not support user installs, we set
      # PIP_USER=0 to not do a user install.
      - name: "Run pre-commit hooks"
        run: export PIP_USER=0; pre-commit run --all-files

  test:
    needs: pre-commit
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python_version: [ "3.11" ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: "Setup Python"
        uses: HassanAbouelela/actions/setup-python@setup-python_v1.4.2 # 1.4.0
        with:
          python_version: "${{ matrix.python_version }}"
          install_args: "--with dev"

      - name: "Run tests"
        run: python -m pytest
