name: "Python CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      PIP_NO_CACHE_DIR: false
      PIP_USER: 1
      PYTHONUSERBASE: ${{ github.workspace }}/.cache/py-user-base
      PRE_COMMIT_HOME: ${{ github.workspace }}/.cache/pre-commit-cache

    steps:
      - name: "Add custom PYTHONUSERBASE to PATH"
        run: echo '${{ env.PYTHONUSERBASE }}/bin/' >> $GITHUB_PATH

      - name: "Checkout repository"
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: "Setup Python"
        id: python
        uses: HassanAbouelela/actions/setup-python@setup-python_v1.4.0 # 1.4.0
        with:
          python_version: '3.x'
          install_args: "--with dev"

      # As pre-commit does not support user installs, we set
      # PIP_USER=0 to not do a user install.
      - name: "Run pre-commit hooks"
        run: export PIP_USER=0; pre-commit run --all-files

  lint:
    needs: pre-commit
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: "Setup Python"
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: "Update packaging tools"
        run: python -m pip install --upgrade pip wheel setuptools build

      - name: "Install dependencies"
        run: python -m pip install --editable .[dev,tests]

      - name: "Check formatting"
        run: black --check src/

      - name: "Run ruff"
        run: "python -m ruff check --format=github src/"

  test:
    needs: lint
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.11" ]

    runs-on: ${{ inputs.os }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: "Setup Python"
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: "${{ inputs.python-version }}"
          allow-prereleases: true
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: "Update packaging tools"
        run: python -m pip install --upgrade pip wheel setuptools build

      - name: "Install dependencies"
        run: python -m pip install --editable .[tests]

      - name: "Run tests"
        run: python -m pytest
